import type { MapInfo, ServerStatus } from "./types";

export const fallbackServerStatus: ServerStatus = {
  servers: [
    {
      id: "j4l-main",
      name: "Jump4Life Main",
      region: "EU",
      domain: "51.210.45.51",
      ip: "51.210.45.51",
      host: "51.210.45.51",
      port: 28960,
      connect: "51.210.45.51:28960",
      hostname: "Jump4Life Main",
      map: "unknown",
      mapid: 0,
      game_type: "COD2",
      players: [],
      player_count: 0,
      online: false,
      password: false,
      error: "Waiting for API data",
    },
    {
      id: "j4l-secondary",
      name: "Jump4Life Secondary",
      region: "EU",
      domain: "51.210.45.51",
      ip: "51.210.45.51",
      host: "51.210.45.51",
      port: 28961,
      connect: "51.210.45.51:28961",
      hostname: "Jump4Life Secondary",
      map: "unknown",
      mapid: 0,
      game_type: "COD2",
      players: [],
      player_count: 0,
      online: false,
      password: false,
      error: "Waiting for API data",
    },
    {
      id: "j4l-third",
      name: "Jump4Life Third",
      region: "EU",
      domain: "51.210.45.51",
      ip: "51.210.45.51",
      host: "51.210.45.51",
      port: 28962,
      connect: "51.210.45.51:28962",
      hostname: "Jump4Life Third",
      map: "unknown",
      mapid: 0,
      game_type: "COD2",
      players: [],
      player_count: 0,
      online: false,
      password: false,
      error: "Waiting for API data",
    },
  ],
  total_players: 0,
  online_servers: 0,
  refreshed_at: new Date(0).toISOString(),
};

export const fallbackMaps: MapInfo[] = [
  {
    name: "jm_bootcamp",
    display_name: "JM Bootcamp",
    type: "jump",
    author: "",
    difficulty: 1,
    timelimit: 30,
    released: null,
    in_rotation: true,
    hidden: false,
    image_key: "jm_bootcamp",
  },
  {
    name: "defrag_crystal",
    display_name: "Defrag Crystal",
    type: "defrag",
    author: "",
    difficulty: null,
    timelimit: 30,
    released: null,
    in_rotation: true,
    hidden: false,
    image_key: "defrag_crystal",
  },
  {
    name: "surf_akai",
    display_name: "Surf Akai",
    type: "surf",
    author: "",
    difficulty: null,
    timelimit: 30,
    released: null,
    in_rotation: true,
    hidden: false,
    image_key: "surf_akai",
  },
];
